name: Deploy FastAPI and Nginx to AWS EC2 via ECR

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 769805549502.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push FastAPI Docker Image
        env:
          ECR_REPOSITORY: website_builder
          IMAGE_TAG: latest
        run: |
          docker build -t website_builder -f Dockerfile .
          docker tag website_builder:latest 769805549502.dkr.ecr.us-east-1.amazonaws.com/website_builder:latest
          docker push 769805549502.dkr.ecr.us-east-1.amazonaws.com/website_builder:latest

      - name: Build and Push Nginx Docker Image
        env:
          ECR_REPOSITORY: website_builder_nginx
          IMAGE_TAG: latest
        run: |
          docker build -t website_builder_nginx -f Dockerfile.nginx .
          docker tag website_builder_nginx:latest 769805549502.dkr.ecr.us-east-1.amazonaws.com/website_builder_nginx:latest
          docker push 769805549502.dkr.ecr.us-east-1.amazonaws.com/website_builder_nginx:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Login to ECR on the EC2 instance
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 769805549502.dkr.ecr.us-east-1.amazonaws.com

            # Pull the latest FastAPI image
            docker pull 769805549502.dkr.ecr.us-east-1.amazonaws.com/website_builder:latest

            # Pull the latest Nginx image
            docker pull 769805549502.dkr.ecr.us-east-1.amazonaws.com/website_builder_nginx:latest

            # Stop and remove existing containers
            docker stop website_builder || true
            docker rm website_builder || true
            docker stop nginx || true
            docker rm nginx || true

            # Create a Docker network
            docker network create app-network || true

            # Ensure directories exist
            sudo mkdir -p /var/www/certbot
            sudo chown -R ubuntu:ubuntu /var/www/certbot

            # Run the FastAPI container
            docker run -d --name website_builder --network app-network \
            -e AUTH_SECRET_KEY=${{ secrets.AUTH_SECRET_KEY }} \
            -e AUTH_ALGORITHM=${{ secrets.AUTH_ALGORITHM }} \
            -e DB=${{secrets.DB}} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
            -e S3_BUCKET_SITES_NAME=${{ secrets.S3_BUCKET_SITES_NAME }} \
            -e S3_REGION=${{ secrets.S3_REGION }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -e APP_ENV=${{ secrets.APP_ENV }} \
            -e SESSION_SECRET_KEY=${{ secrets.SESSION_SECRET_KEY }} \
            769805549502.dkr.ecr.us-east-1.amazonaws.com/website_builder:latest

            # Run the Nginx container with volume mounts
            docker run -d --name nginx --network app-network \
              -p 80:80 -p 443:443 \
              -v /etc/letsencrypt:/etc/letsencrypt \
              -v /var/www/certbot:/var/www/certbot \
              769805549502.dkr.ecr.us-east-1.amazonaws.com/website_builder_nginx:latest
